---
title: Examining Acts 2;38
bibliography: merged.bib
categories: []
---
<!-- date: -->

-------

> <r r="Acts 2 38">"Then Peter said unto them, Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost." (Acts 2:38)</r>

********************************
** Move Acts 2:38 examination to a separate article and reference it**
## An examination of Acts 2:38
It's important to understand context when attempting to derive doctrine from verses. One verse with many complex interpretations is Acts 2:38. I think the context here should make us more aware of improper interpretations, can show us how important it is to examine the tools each of us use when evaluating scripture, and can show us how easily cherry picking verses without trying to understand them can lead our theology astray.
// &emsp;I've shown above why confession precedes forgiveness. How do we know that forgiveness precedes repentance? I believe the answer is in Acts 2:38<r c="Acts 2 38">@Acts_2:38</r>, which says to repent and be baptized for the remission of sins.

> <r r="Acts 2 38">"Then Peter said unto them, Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost." (Acts 2:38)</r>

### What does "For the remission of sins" mean?
&emsp;The word "for" here in the phrase "for the remission of sins" is translated from the Greek word "eis". As with many sections of the word, there's a division between many believers about what this word means, and the different interpretations lead people to believe differently about what is required for salvation. This is because "for" has different meanings depending on the context. Some take the interpretation, "Repent and be baptized in order to obtain the remission of your sins."; others take, "Repent and be baptized in response to the remission of your sins.". As it's often explained, one can take medicine for an ailment; in this example, "for" means "in response to the ailment", not "to obtain the ailment". Our modern English dialects would tend to lend to Acts 2:38 meaning, "to obtain", but I believe it has to be interpreted, "in response to". There are actually a few words that change how this verse is interpreted, depending on the assumed definition: "for", which I mentioned, "baptism", and "remission". However, the definitions chosen for "baptism" and "remission" correspond to the way "for" is interpreted, so the complexity isn't too large to attempt to explain here.

&emsp;Since this article is focused on confession, forgiveness, and repentance, I'll reference another article to explain that baptism is not required for obtaining salvation [Is Baptism Required for Salvation](../isBaptismRequiredForSalvation/isBaptismRequiredForSalvation.qmd).

&emsp; Before continuing, I'll try to explain what "remission" means in this verse when used with the definition of "for" as "in order to receive". This kind of "remission" would be that sins have gone away, similar to how a disease can be in remission. Some people would, for that reason, attempt to use this verse as evidence that Christians have forgone all sin, and that if you ever sin, you can't be considered to have ever been a true Christian. Along with this definition of "remission", a definition of "repent" as "turn away from your sins" is also used. If these definitions are taken together, the verse appears to say, "Stop sinning, and be baptized, in order to receive your ability to continue not sinning". If repentance and remission were to mean the same thing as in this example, there would be a needless redundancy in the verse; this leads me to doubt this interpretation. Also, if Christian's were supposed to be sinless at this point in time, the Word would not need to tell us to confess to each other, or how to handle Christians sinning against each other, such as referenced above in Matthew<r c="mt 18 15 17">@Matthew_18:15-17</r> and James<r c="jm 5 16">@James_5:16</r>. Another definition is that the "remission" is the forgiveness of sins that comes when you repent and are baptized, which has the premise that forgiveness, and therefore salvation, are dependent on repentance and baptism. The idea that remission means forgiveness seems to be correct in some sense, but I'd like to try to give a more specific definition, and also explain why I don't believe that salvation is dependent on repentance and baptism, although I do believe they're expected of Christians.

&emsp;It's clear to me that "remission" is referring to "remittal of payment" for our sin, and perhaps also the resulting forgiveness of sin that was an effect of that payment. The reason I say remittance of payment is simply that remission refers more so to remitting payment for a debt, while forgiveness can be misconstrued as simply rendering a debt to be non-existent. Jesus's sacrifice was a payment for our sins; so, our sins were not simply ignored, our counted as nothing; there truly was a payment that nullifies a Christian's sin in the eyes of God. I suspect that modern English translations changed the word "remission" to "forgiveness" because of the modern definition of remission as "abatement". "Forgiveness" is pretty clearly referring to a debt of some kind being rendered null, although even its biblical connotation has been polluted recently as meaning "universal forgiveness".

&emsp;To make the argument that remission doesn't mean that Christians are no longer able to sin, and that it doesn't mean they won't ever fail when tempted, I'd reference:

> <r r="ro 3 24 25">"Being justified freely by his grace through the redemption that is in Christ Jesus: Whom God hath set forth to be a propitiation through faith in his blood, to declare his righteousness for the remission of sins that are past, through the forbearance of God;" (Romans 3:24-25)</r>

The above passage says our justification is in Christ, that he's our propitiation (offering to pay for our sin) through his blood, and that this shows that his righteousness was to pay for our sins which were forborne (overlooked for a time).

> <r r="heb 9 22">"And almost all things are by the law purged with blood; and without shedding of blood is no remission." (Hebrews 9:22)</r>

The above verse refers to sacrifice under the old testament law. The life of the flesh is in the blood<r c="lv 17 11">@Leviticus_17:11</r>, and so requiring sacrifice shows that transgressions of the law requires bloodshed in payment. In place of your blood, since the wages of sin are death<r c="ro 6 23">@Romans_6:23</r>, another's blood can be spilled. This old testament sacrifice ensures that we understand that Christ's blood was spilled, his life was given, so that we could live, and this refers to spiritual life as well. So, when the Word says that Christ's blood was spilled for the remission of sins,

> <r r="mt 26 28">"For this is my blood of the new testament, which is shed for many for the remission of sins." (Matthew 26:28)</r>

we can be sure it means that the remission was truly payment for our sins, which means remission is not referring to the abatement of our sins, or that we are unable to sin.
***************************
**
&emsp;Further criticism of remission in the Bible being defined as abatement of sin can be done by simply examining what the Word says about Christians. We are not guaranteed to be sinless, and we are assured by our faith that we are saved, so we aren't to be afraid of condemnation when we do sin, but we are to confess our sins to God as in The Lord's Prayer.
https://www.youtube.com/watch?v=s2olQEz1sPE
** expound on the above statement** **

In case there is still any question about whether this is what remission means, the context surrounding the verse in the chapter should make it clear. Peter is explaining to the men of Israel that they had crucified Christ<r c="ac 2 23">@Acts_2:23</r>, and that Christ was the Lord<r c="ac 2 23 27, ac 2 30, ac 2 36">[@Acts_2:23-27; @Acts_2:30; @Acts_2:36]</r>. Therefore, they were to repent and be baptized in the name of Jesus after putting their faith in Christ as their redeemer<r c="ac 2 38">@Acts_2:38</r>. Here's some of the surrounding context:

> <r r="ac 2 22 39">"Ye men of Israel, hear these words; Jesus of Nazareth, a man approved of God among you by miracles and wonders and signs, which God did by him in the midst of you, as ye yourselves also know: Him, being delivered by the determinate counsel and foreknowledge of God, ye have taken, and by wicked hands have crucified and slain: Whom God hath raised up, having loosed the pains of death: because it was not possible that he should be holden of it. For David speaketh concerning him, I foresaw the Lord always before my face, for he is on my right hand, that I should not be moved: Therefore did my heart rejoice, and my tongue was glad; moreover also my flesh shall rest in hope: Because thou wilt not leave my soul in hell, neither wilt thou suffer thine Holy One to see corruption. Thou hast made known to me the ways of life; thou shalt make me full of joy with thy countenance. Men and brethren, let me freely speak unto you of the patriarch David, that he is both dead and buried, and his sepulchre is with us unto this day. Therefore being a prophet, and knowing that God had sworn with an oath to him, that of the fruit of his loins, according to the flesh, he would raise up Christ to sit on his throne; He seeing this before spake of the resurrection of Christ, that his soul was not left in hell, neither his flesh did see corruption. This Jesus hath God raised up, whereof we all are witnesses. Therefore being by the right hand of God exalted, and having received of the Father the promise of the Holy Ghost, he hath shed forth this, which ye now see and hear. For David is not ascended into the heavens: but he saith himself, The Lord said unto my Lord, Sit thou on my right hand, Until I make thy foes thy footstool. Therefore let all the house of Israel know assuredly, that God hath made the same Jesus, whom ye have crucified, both Lord and Christ. Now when they heard this, they were pricked in their heart, and said unto Peter and to the rest of the apostles, Men and brethren, what shall we do? Then Peter said unto them, Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost. For the promise is unto you, and to your children, and to all that are afar off, even as many as the LORD our God shall call." (Acts 2:22-39)</r>

Before trying to summarize verse 38, I'd like to make a key point that I think should bring some clarity to the context.

> <r r="ac 2 1">"And when the day of Pentecost was fully come, they were all with one accord in one place." (Acts 2:1)</r>
>
> <r r="ac 2 5 6">"And there were dwelling at Jerusalem Jews, devout men, out of every nation under heaven. Now when this was noised abroad, the multitude came together, and were confounded, because that every man heard them speak in his own language." (Acts 2:5-6)</r> 

&emsp;There were two groups being spoken of in Acts 2. The first group mentioned in verse 1 consisted of the roughly 120 disciples from chapter 1<r c="ac 1 15">@Acts_1:15</r>. The second group referred to as "the multitude" appears to be these devout Jews in Jerusalem from many places that came together because they heard the noise of the disciples speaking in tongues. Despite these Jews having many different native languages<r c="ac 2 7 11">@Acts_2:7-11</r>, and the disciples being Galilaeans who wouldn't know all of these languages, the Jews heard the disciples speaking in their native languages. The point of noting this is that everyone involved in this event was considered to have believed in the God of the Old Testament. I do believe that this means at least some of the Jews may have been saved already, and that they're simply being called to put their faith in Christ as Lord. This is why the Spirit of God led the disciples to speak in tongues, so that those who understood other languages could hear the good news of Christ, and repent --- in this case, to change their mind about God by putting their faith in Christ whom the Jews had killed. He reminds them of the promise that God gave in the Old Testament, that Abraham's Children would number as the stars<r c="gn 15 5">@Genesis_15:5</r>, and that as many of their own children as God would call would be a part of that. The promise referred to is the one given during the Old Testament to the "seed" of Abraham<r c="ga 3 16">@Galatians_3:16</r>. We are co-heirs<r c="ro 8 17">@Romans_8:17</r> in this promise, of God's kingdom, that was to Christ<r c="ga 3 16">@Galatians_3:16</r>, by becoming the children of God<r c="ro 8 16">@Romans_8:16</r> as well when we put our faith in Christ's sacrifice for us<r c="jn 3 16">@John_3:16</r>. I believe mentioning this promise also points to the idea that the Jews may have been saved despite not having put their faith in Christ up to this point, because researching the "promise" leads to the question of who could be saved, and how they would be saved, in Old Testament times which were before Christ's sacrifice; see [Old Testament Salvation](../oldTestamentSalvation/oldTestamentSalvation.qmd).

&emsp;The point of mentioning this interpretation is that many people interpret this passage as showing people how to be saved, when it may have been pointing Jews who believed in God for their justification --- and therefore would be saved by this faith in Him even before knowing the name of Christ --- to then put their faith in Christ as Lord. This justification before having known the name of Christ would match Abraham's. Upon hearing the good news of Christ, one who believes the God of the Old Testament cannot deny Christ's person and work, and one can only benefit from hearing it because their subsequent belief in Christ would allow them to receive the Holy Spirit <r c="Ep 1 13 14">@Ephesians_1:13-14</r>. There are also two more points that come from the idea that the Jews referenced may have already been justified by faith. One --- this interpretation would suggest that Acts 2:41,

> <r r="ac 2 41">"Then they that gladly received his word were baptized: and the same day there were added unto them about three thousand souls." (Acts 2:41)</r>

speaks of these Jews being added to the Christian church and receiving the Holy Spirit, and not necessarily that their status of justification before God had changed. Some translations do say "souls" were added, and some people interpret that to mean that they were saved. The King James version says "souls" were added to "them". Other translation say the additions were to "them", the "church", the "body", "their number", etcetera. This suggests to me that the occurrence of "souls" was referring to the people's identities, and wasn't making a statement about their justification. Two --- this interpretation also seems to negate another support for baptism being a prerequisite for salvation, since the other interpretation of verse 41 would seem to read that these Jews were saved as a result of their baptism.

**When mentioning the word "for" and what it means as "at", or "unto" (in response to), a parallel to Acts 2:38 is Mark 1:4, which uses the same phrasing with "eis". Gill says here https://biblehub.com/commentaries/gill/mark/1.htm that this means "unto" forgiveness. Also, per Gill, John wouldn't baptize a given person until they had repented.**

