---
title: Image of God
# bibliography: merged.bib
categories: [kingdom mindset]
draft: true
---
<!-- date: -->
# The image and glory of God
&emsp;We are made in the image of God.

> <r r="ge 1 26 27">"And God said, Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the fowl of the air, and over the cattle, and over all the earth, and over every creeping thing that creepeth upon the earth. So God created man in his own image, in the image of God created he him; male and female created he them." (Genesis 1:26-27).</r>

Why does the Word say God made "man" in his own image, and continue to use "them" for the same subject in the next verse? Some translations use the alternate meaning of the word translated as "man" to express that it refers to mankind as a whole in this instance, including both man and woman. This would mean that man and woman were made in the image of God. At first, this may seem to contradict the next verse:

> <r r="ge 1 27">"So God created man in his own image, in the image of God created he him; male and female created he them." (Genesis 1:27).</r>

This verse says that the man was made in the image of God without mentioning the woman. Why does it not say that God created both man and woman in his own image if the previous verse truly refers to both man and woman? Could it be that "man" referred only to adam, while "them" referred to his male descendants which were yet to come? Wouldn't this mean woman has not been made in the image of God, which verse 27 can seem to agree with? We do get further clarification on this in chapter 2, when creation is covered in more detail. Let's look more closely at how the woman was made.

> <r r="ge 2 21 24">"And the LORD God caused a deep sleep to fall upon Adam, and he slept: and he took one of his ribs, and closed up the flesh instead thereof; And the rib, which the LORD God had taken from man, made he a woman, and brought her unto the man. And Adam said, This is now bone of my bones, and flesh of my flesh: she shall be called Woman, because she was taken out of Man. Therefore shall a man leave his father and his mother, and shall cleave unto his wife: and they shall be one flesh." (Genesis 2:21-24).</r>

We see here that woman was not made directly in the image of God as the man was, but as a part of the image of God, out of the man's very flesh; this is why Genesis 1:27 doesn't say that both man and woman were created in the image of God. Man was made in the image of God, and then woman was made from man as a part of his complete image, and mankind is the complete image of God. Woman was made, if you will, as a subset of the image of God, and this is why they're to be joined together in marriage: to be one complete body. This means much more when we understand that we are reflections of God (since we are made in his image) and that Christ has his own bride in his body: those who are of faith, who he is one with in spirit. That Christ has his own bride in his people is also why Israel is considered to have committed spiritual adultery when worshiping idols[^je 3 8].

[^je 3 8]: "And I saw, when for all the causes whereby backsliding Israel committed adultery I had put her away, and given her a bill of divorce; yet her treacherous sister Judah feared not, but went and played the harlot also." (Jeremiah 3:8).


# Who is your mother?
- mother god cult vs the feminine counter part to Christ which is the church
- the mother which is the body of Christ vs the mother which is the world
	- https://www.youtube.com/watch?v=L_dIaeNu0JI

# The head directs the body, and the body submits
uemsp;Western culture currently holds the dogma that there is no difference between men and women. Christians who agree with modern gender ideology may recognize that God saying "Let us make man" means that the plurality (the "us") was making mankind in their image. However, rather than recognizing that this plurality is the trinity, including Jesus, who existed before Abraham[^jn 8 58], they may be inclined toward the interpretation that the plurality is a Father and Mother God who together created both man and woman in each of their images respectively. In this view, both "Gods" rule together, and are equal, which supports feminist egalitarian doctrine. Those who believe this may as well say, "Ignore that the Word only ever metions God the Father, and that the Mother would have to be the other believers within the body of Christ, since he is God, and believers within his body are his bride. We'd like to read our own worldview into the Word of God because we know truth better than our own creator.". However, when we see that God is the head, and his bride is his body, and understand that our own heads direct our bodies, then we understand that God directs his own body of believers, and that they submit to his will. So, when the word says that the husband is the head of the wife, then we should recognize that the the wife is the body of the husband - with her head directing her - and that this is why the word says, <r r="ep 5 22">"Wives, submit yourselves unto your own husbands, as unto the Lord." (Ephesians 5:22).</r>

[^jn 8 58]: "Jesus said unto them, Verily, verily, I say unto you, Before Abraham was, I am." (John 8:58).

> <r r="ep 5 22 24">"Wives, submit yourselves unto your own husbands, as unto the Lord. For the husband is the head of the wife, even as Christ is the head of the church: and he is the saviour of the body. Therefore as the church is subject unto Christ, so let the wives be to their own husbands in every thing." (Ephesians 5:22-24).</r>


&emsp;Man is the head of a marriage under God. How our world and the women in it fight this, even women of faith. The desire of the woman is "for" her husband, or, to take her husbands authority.


[^1 co 11 9]: "Neither was the man created for the woman; but the woman for the man." (1 Corinthians 11:9).


Transgenderism seeks to invert and polute the meaning of God's image in men and women more literally through dismembering and carving the body to satisfy a lie.
