---
title: Our Value in Christ
categories: [kingdom mindset]
draft: true
---
<!-- date: -->
## Our Value in Christ

The price which Christ paid for us is something we must keep in mind continually. Continuing from the ideas of the [about](../../../about/about.qmd), we understand our value, meaning, and purpose more clearly when we know for certain what God paid for our opportunity to be made right with him. "...you were bought at a price." (1 Corinthians 6:20). His [sacrifice](../sacrifice/sacrifice.qmd) displays how much he was willing to pay for those who put their faith in him.

The world is full of people who don't understand that they were created for a purpose, by glorious God who seeks to be in covenant relationship with them. God offers his promises to us out of his goodness. If one seeks him within his word then one finds both their value of self, and purpose. We were created to give and receive love, and to give glory to God. This doesn't sound very important to most, but most don't know how good God's love is, and how good it is when we reflect it. This is something that one can only learn through the word which describes who God is, and through relationship with God as one walks with him.

Not only do we have a redeemer, but God makes us into a part of his familial kingdom. We live under the blessings of God as part of his kingdom, and eternity in his kingdom is what we have to look forward to, no matter how much we suffer in the world; long-suffering is actually a part of sacrificing out of love.

> <r r="Ro 8 15 17">"For ye have not received the spirit of bondage again to fear; but ye have received the Spirit of adoption, whereby we cry, Abba, Father. The Spirit itself beareth witness with our spirit, that we are the children of God: And if children, then heirs; heirs of God, and joint-heirs with Christ; if so be that we suffer with him, that we may be also glorified together." (Romans 8:15-17).</r>

This means so much more than the ignorance of purpose and value that most people live with. We have a creator; He has saved us, shown us true love and goodness, and invites us to participate in His good work and give glory to Him.
