---
title: Positional Forgiveness
bibliography: merged.bib
categories: [relationships]
draft: true
---
<!-- date: -->

After mentioning the question of why we confess after already being forgiveness, continue.

****Move to positional forgiveness article
##### Sealed with the Holy Spirit
&emsp;If one has only considered there to be one kind of forgiveness, and so believes that unconfessed sin threatens salvation, then one of the first big questions I'd expect against this is, "If a Christian is sealed with the Holy Spirit, how could they be unforgiven and disassociated with by God and the Church? Wouldn't this suggest that they could somehow be unsealed, or unsaved?" I think the answer to this is that Christians are sealed<a href="link to once saved always saved article"></a>, and again, that our justification, or salvation, is dependent only on our faith in Christ's work<a href="link to justification by faith"></a>. I don't think dissociation would then affect salvation, only fellowship. One could bring up against this,

><r r="1 co 5 1 5">"It is reported commonly that there is fornication among you, and such fornication as is not so much as named among the Gentiles, that one should have his father's wife. And ye are puffed up, and have not rather mourned, that he that hath done this deed might be taken away from among you. For I verily, as absent in body, but present in spirit, have judged already, as though I were present, concerning him that hath so done this deed, In the name of our Lord Jesus Christ, when ye are gathered together, and my spirit, with the power of our Lord Jesus Christ, To deliver such an one unto Satan for the destruction of the flesh, that the spirit may be saved in the day of the Lord Jesus." (1 Corinthians 5:1-5)</r>

to suggest that dissociation would result in the destruction of flesh so that one would confess in order to be saved. My main argument against this would be that another section uses similar phrasing about delivery unto Satan when referring to two people, without mentioning expulsion from the church:

><r r="1 ti 1 18 20">"This charge I commit unto thee, son Timothy, according to the prophecies which went before on thee, that thou by them mightest war a good warfare; Holding faith, and a good conscience; which some having put away concerning faith have made shipwreck: Of whom is Hymenaeus and Alexander; whom I have delivered unto Satan, that they may learn not to blaspheme." (1 Timothy 1:18-20)</r>

This seems to be why John Gill says about both of these occurrences (of delivery unto Satan) that it was not by excommunication, but was by apostolic power [@gill_1_nodate; @gill_1_nodate-1].

##### Unforgiving servant
- Mathew 18 says unless you forgive, you'll be treated by God as the one who was turned over to the torturers until his debt was paid. Sin is unpayable unless paid by Christ, so this would seem to mean the unforgiving person who calls themselves forgiven would be cast into the lake of fire with unbelievers. See Gill's notes on on matthew 18 34, they give a potential explanation. Perhaps the suggestion is that a sealed person couldn't fail to forgive.

##### Cast into the fire and burned
- John 15 6 says one can be cast into the fire and burned. The verse before this speaks of a branch in Christ, making it seem to some that one who abides could then not abide, and lose their salvation. However, the "taking away" means "lifted up" into the light so that it may bear fruit.
	- https://www.evidenceunseen.com/bible-difficulties-2/nt-difficulties/john-acts/jn-156-does-this-passage-teach-that-believers-will-be-sent-to-hell-for-not-bearing-fruit/

The last two criticisms seem to go against once saved always saved doctrines unless it's assumed that these were never real believers in the first place, which may be the case.
OSAS definition of eternal life will need to be addressed. Is eternal life received forever, or is it held while you believe to be received later while being lost if you lose faith. Verse about already having passed from death to life, which would be eternally granted if the eternal life has already been received.
https://www.youtube.com/watch?v=vvxR-MHcukk
https://youtu.be/n4mtCPNTG64

1 john 1 3 10 is used to suggest positional forgiveness due to the use of "fellowship" several times, but this message ignores the conditionals.
	1 John 1 7 says, "But if we walk in the light, as he is in the light, we have fellowship one with another, and the blood of Jesus Christ his Son cleanseth us from all sin." Since there was no punctuation, I think this could be interpreted, "If we walk in the light, as he is in the light, then we will have fellowship with one another; also, the blood of Jesus Christ his Son cleanses us (those who are in this faith and fellowship) from all sin." This would suggest rather than, "We, as believers, will only be saved if we walk in light", that "As believers, we walk in light, and have fellowship, and are cleansed from unrighteousness by the blood of Jesus. Unbelievers will not do so, nor are they cleansed by Jesus's blood."
	Does 1 John 1 10 suggest that those who don't confess sin aren't saved in the first place?
		This would suggest that 1 john 1 6 would be referring to the concept: those who claim faith but show no fruit are not actually of faith in Christ.

End of matthew 18 does show confession, and then either forgiveness or unforgiveness, and the consequence for unforgiveness. Is this consequence eternal punishment for those who don't forgive when confessed to by their family in Christ? Could it rather be be the scourging of one who doesn't bear fruit, heb 12 6?
*******
