---
title: Sacrifice
categories: [relationships]
draft: true
---
<!-- date: -->

## Sacrifice
&emsp;When we understand how much the Father sacrifices to offer his love to us, we can begin to love as he does. This includes loving God, ourselves, and others, and actively becoming a living sacrifice for the benefit of all of them: "...in view of the mercies of God, I urge you to present your bodies as a living sacrifice..." (Romans 12:1). "How is sacrificing our lives loving to ourselves?", you might ask, since sacrifice costs us. This question is moot when we realize that God has offered the ultimate love for us to accept. When we have faith, we receive the Spirit of God, which influences us according to his love. If his love is sacrificial, we also will to sacrifice our life to God and for others as he does. This sacrifice ultimately shows God's love, and his love is to our benefit; ultimately, <r r="1 John 4 19">"We love him, because he first loved us." (1 John 4:19).</r>. So, in showing the love shown to us, we sacrifice.


#### Both giving, and receiving sacrifice
&emsp;How much do we sacrifice, then? Do we even sacrifice our lives, not as a living sacrifice, but a final sacrifice of our breath and body? We should be willing to for the sake of others, if it would truly glorify God. However, our lives are not to be offered arbitrarily, since we are to love ourselves. We're still to provide for ourselves, and our family, since the word asserts we are to provide for our households, "...if anyone does not provide for his own family, especially for his own household, he has denied the faith and is worse than an unbeliever." (1 Timothy 5:8). We can only do that if we first care for ourselves, but we are always willing to sacrifice what we can for the sake of others, even to the point of making concessions for their convictions; in the context of speaking about wounding the conscience of a weaker believer who believed they shouldn't eat meat, Paul says, "Therefore, if what I eat causes my brother or sister to fall into sin, I will never eat meat again, so that I will not cause them to fall." (1 Corinthians 8:13). A good point of clarification in giving up rights like this is that we still must be given the right to our freedoms in order to sacrifice them. We must be able to choose to exercise our rights; otherwise, they're not rights. However, love compels us to voluntarily sacrifice the exercising of them, for the sake of others. In situations where your rights are forcefully taken, you've been sinned against, and sin against you requires that the offender confess to you so that you can forgive them, and sin also requires that they repent of their sin. <a>(Link to requirement that rights are given, but freely sacrificed for others out of love) (Link to repentance)</a>. The Spirit understands true sacrifice for the benefit of others, and both parties involved appreciate it. The one receiving is truly appreciative to receive, and the one giving does it for the sake of the recipient. In this example, loving sacrifice cannot be forcibly taken, or given. The one taking is not doing so selfishly, or out of compulsion to accept, and the one giving is neither compelled to outside of their will, nor doing so in expectation of something in return.

&emsp;God's sacrifice for us should always be on our mind because it compels us to truly appreciate the sacrifice of others when we see it reflect Christ; it inspires us to give in the same manner. In a world where people seek to fulfill themselves at the expense of others, this contradicts the world, but it makes a statement which people don't see outside of Christ. True loving sacrifice shows people in this lost and hopeless world what they were originally made for within union with God. If it weren't for the fall, everyone would treat each other with love, and without sin. This is what Christ points everyone to, but people of the world take offense at this message because they must first give up their pride by admitting to sin, repent from said sin while they still will for it, and then sacrifice their will for Christ's. The world views this lack of pride, and willing sacrifice, as weak.
