---
Title: Why Christianity?
categories: [faith]
bibliography: merged.bib
date: 2024-10-01
---

# Why Christianity?

&emsp;Why should we believe Christianity over the plethora of other religions, or even atheism? Many believe the most rational position to hold on worldview is believing in nothing by default. However, if we have compelling evidence to the contrary, suggesting that there is a God, and that it's the Christian God, then it would be made obvious that those assumptions hold their own form of faith and bias.

&emsp;No matter what we believe, we collectively struggle to answer questions of worldview about where we came from, why we're here, how we should behave while we're here, and what happens when we die. Why do we have these questions? Because we can't directly observe the origin of the universe. Because only the creator of the universe could tell us why we are here. Because only a perfect one could give us non-relativistic morality. Because no one can report back their experience of death after experiencing it. So, we have a multitude of explanations for worldview, and we must ask which answers to those questions are correct. Fortunately, the Christian God has provided evidence far beyond any reasonable doubt of His existence, and has proven that Christian scripture is inspired by Him. I think we can verify this by examining biblical prophecy, biblical history, and eyewitness testimony.

&emsp;Why do I choose these topics? History, supported by archaeology and historical documentation (by secular and non-secular historians), agrees with the Biblical accounts. History also records the details of the fulfillment of biblical prophecy, and eyewitness testimony confirms this fulfillment. What you end up with are overlapping proofs. So, certain biblical events are historically recorded, even outside of the bible, while they also fulfill biblical prophecy, and are confirmed by eyewitnesses (even unto their death which was due to their faith) to have happened. I hope the significance of this is apparent. An attack on one of these points leaves the other two still standing in defense of it. If an attack comes against the eyewitness testimony of the death and resurrection of Christ, for example, His historical fulfillment of prophecy still supports His divinity, and history confirms His death on the cross and that the tomb was found empty.

## The overlap with Jesus

&emsp;Before continuing, I'd like to specifically point out the prophetic, historical, and testimonial details that apply to Jesus, which I'll also provide evidence for in this article. Prophecy foretold of the coming Messiah's (savior's) life, death, and resurrection; Jesus fulfilled these prophecies. Jesus's life, and death, and the tomb being empty after His death are all supported by historical documentation. The Gospels, written by four of the twelve disciples, record corresponding accounts of their experiences with the living Jesus, and about His death, and they explain that the twelve disciples claim to have seen Jesus risen from the dead. We know that eleven of these twelve eyewitnesses claimed this even unto their own murders. Hopefully the significance of this overlap between the prophecy, history, and eyewitness testimony unto martyrdom is clear, which is that they lend to the credibility of each other so that each topic can't be discounted without disproving the other two. While each of the topics can stand on its own, they're also able to defend each other. I believe these topics were intentionally laid out by God for us to discover, just as He caused Jesus to become our redeeming sacrifice, so that we can have a proper undeniable evangelistic message in order to lead others to faith.

## Biblical History

&emsp;The Bible accurately records history. Many historical figures are recorded in the Old Testament and New Testament [@usefulcharts_37_2023; @usefulcharts_28_2023]. No point of secular history has contradicted its historical claims, and many points of contention have been disproved. There are many examples, but one is Belshazzar, who was recorded in the Bible, but was claimed to have been fabricated, until the Nabonidus Cylinder was found, confirming his historical existence [@mike_winger_defending_2016; @jmclatchie_authenticity_2021].

&emsp;Some have even disputed the existence of Jesus. However, several historians recorded details about Jesus that fit the Bible. Tacitus was a Roman historian and politician. His annals confirm that he knew Jesus was crucified under Pontius Pilate, as the Bible describes. Flavius Josephus, a Jewish historian, also confirms the same, as does Celcus, a Greek philosopher and opponent of Christianity. The Bible claims there was a darkness over the land around the time of Jesus's death<r c="lk 23 44, mt 27 45">[@Luke_23:44; @Matthew_27:45]</r>. Thallus, and Phlegon van Tralles were both historians who mention this darkness @versebyversebt_is_2010. Julius Africanus disputes Thallus's explanation for the darkness, which was that it was caused by an eclipse @versebyversebt_is_2010. Since Jesus was crucified on the day of preparation for Passover, and the Passover celebration is based on the lunar calendar which the Jews followed, the timing dictated that the moon was in a position that couldn't have caused an eclipse; it would've been on the opposite side of the Earth. The point in noting this dispute is to show there was a serious historical discussion about the physical darkness which occurred around the time of Jesus's death. The Bible also claims that the Earth quaked when Jesus died, and that the veil was torn<r c="mt 27 51">@Matthew_27:51</r>. The earthquake that was recorded to have caused damage to the Jewish temple in 33 A.D. could explain the tearing of the veil @cris_putnam_earthquake_2011.

<!-- That the time of Jesus death (look for verification Mike talks about that the date of his death was historically recorded) was according to the lunar calendar of the passover, a denial that an eclipse was possible. -->

&emsp;The Bible records that the Jewish claim made to counter Christianity was that the disciples stole the body of Jesus; this claim is documented by the Jewish Talmud @mike_winger_evidence_2016, and Justin Martyr in his debate with the Jews on the subject @mike_winger_bunch_2019. This claim that Jesus's body was stolen concedes that the Tomb was indeed empty, and it's still often claimed by the Jews to this day. The emptiness of the tomb requires an explanation, but no good explanation has been given aside from Jesus's resurrection. That eleven of twelve disciples went to their death for the faith, with the basis of this faith being that Jesus is risen, is evidence enough that they weren't lying, and truly believed they had seen the risen Christ. Other explanations that try to explain this away create their own issues @mike_winger_evidence_2016-1.

<!-- https://www.youtube.com/watch?v=Y4cUZkXQaQg
https://www.youtube.com/watch?v=5Xil20H9yPE
https://www.youtube.com/watch?v=A6uWSoxG_Fs -->

&emsp;There's other support for biblical history, such as undesigned coincidences. Charles Leslie's framework suggests that Jewish history, and Jesus's resurrection celebrations set up ongoing tradition based on public events that couldn't have been made up later. You wouldn't convince the Jews that their history is fake, because they have a record of their history and the continued occasions made to remember them @testify_can_2024.

## Eyewitness testimony

&emsp;Jesus's disciples were eyewitnesses of Jesus's death and resurrection. They would've known whether they had made up this story, and surely wouldn't have died for it if it were a lie. However, church history supports that they were tortured, and we're told by the early church that eleven of the twelve were killed for their faith, with the other one being exiled. We also have other historical support for the martyrdom of three apostles: Peter, James, and Paul (Paul not being one of the twelve disciples) @mike_winger_how_2019. Perhaps one person could be deemed to have been willing to die for a lie because of insanity, but the chances of eleven people dying for a lie when they certainly would have known better are essentially non-existent. So, we know the disciples truly believed they had seen the risen Christ. Multiple of them attested locally in Jerusalem, and soon after the time of the crucifixion, which means the claims were made in the place where and time when people would have been most likely to have the evidence to prove them wrong if it weren't so. This is more reason to believe they weren't crafting a fable. Luke says they saw Christ risen<r c="lk 24 31">@Luke_24:31</r>. Paul also claims Jesus appeared to Peter, then the twelve disciples, then more than 500 people, then James, then all the apostles, before finally appearing to Paul himself<r c="1 co 15 5 8">@1_Corinthians_15:5-8</r><sup>,</sup> @mike_winger_how_2019.

&emsp;I already mentioned the empty tomb under the biblical history heading, but we also have eyewitness testimony of it. The four gospels claim that women found the tomb empty, which is unlikely to be false because women's testimony wasn't trusted at the time. It claims Peter and some other men<r c="lk 24 12, lk 24 24">[@Luke_24:12; @Luke_24:24]</r> saw the empty tomb as well. Some take issue with this eyewitness testimony coming from the Bible. However, since we know the disciples were willing to give their lives for their faith, with the basis of this faith being that Christ is risen, we can have the utmost confidence that they truly believed the claim [@versebyversebt_is_2010; @mike_winger_bunch_2019; @mike_winger_evidence_2016-2].

## Prophecy

&emsp;Some believe that the Bible's historical prophecies were written after they happened because the events they describe have been clearly fulfilled historically. However, many prophecies in the Bible are known to have been written before they were fulfilled.

&emsp;We have historical fulfillment of the prophecies of Tyre. This prophecy, in Ezekiel 26, explained how Tyre would fall, despite it being considered impregnable. It explained that many nations would come against it in waves, its walls and towers would be destroyed by Nebuchadnezzar, that it would be cast into the sea, being scraped flat like a rock, that fishermen would cast their nets there, and that its daughter villages would be slain by the sword; it was also noted that the city wouldn't be rebuilt. Nebuchadnezzar's siege, and following destruction of the mainland city proceeded as it was written. Much later, Alexander the Great eventually succeeded in building a causeway to the island city by casting the formerly destroyed mainland city into the sea. He then killed the island city residents. Since then, the area has been used for fishing. A city named "Tyre" exists near by, but the original city is still either at the bottom of the sea, or in ruins at the island, and the city, as it was, was never restored. Alexander founded Alexandria which replaced the role of Tyre. The story of Tyre's destruction is well-documented historically, and since we know the prophecy was written before it happened, opponents often claim that the prophecy wasn't completely accurate in some way, such as by saying a city named Tyre still exists, which I've already explained [@mike_winger_destruction_2016; @david_guzik_enduring_2017].

<!-- We also have the prophecy of Cyrus. -->

<!-- Prophecy of Daniel - kingdoms of the statue of 4 metals, their fulfillment, Josephus's recognition of this fulfillment. -->
&emsp;We have the prophecy of Daniel 7 and 8. In this prophecy, Daniel shares a prophetic dream about four beasts, which represented four kingdoms and the events that would occur in them. Three of the kingdom's events came to pass over the course of several hundred years, with the fourth kingdom's prophecy being left for the future. The dates of the proclamation of these prophecies are confirmed (by the dead sea scrolls) to be before many of the events happened [@mike_winger_fulfilled_2016; @mike_winger_defending_2016-1; @jmclatchie_authenticity_2021]. The timing of the Messiah's coming is predicted in Daniel 9. In the Bible, Jesus mentions it and how he would fulfill the prophecy about the son of man by being "cut off", and also confirms that the Jewish temple would be destroyed after this, which we know happened in 70 A.D. We know these events occurred in the specific years which they were predicted to happen in by Daniel, and it's clear that this was written well before Christ was born [@mike_winger_daniel_2016; @jmclatchie_authenticity_2021].

&emsp;The Messiah was prophesied of in Psalm 22, which was written well before He was born @mike_winger_really_2019. Psalm 22 gives 16 points of correspondence in prophecy of the crucifixion of Christ. It should be noted that Christ, while on the cross, quoted the beginning of this passage which describes His crucifixion. It's also unlikely that this quote could've been made up, because the eyewitness testimony is already explaining what we know to have happened historically --- that Christ died on the cross. The point is: there's no reason to doubt that Jesus quoted the prophecy of his crucifixion if the doubt is simply because it's not recorded by a secular historian. We know the prophecy already existed in Psalm, and we know that Christ fulfilled it historically because His crucifixion was recorded; so, there's no reason for Christ's quote to have been fabricated. This is a slight edit of a list from Mike Winger which describes the points of correspondence between Psalm 22 and the crucifixion of Christ @mike_winger_really_2019:

1. He is forsaken while others are saved<r c="ps 22 1 6">@Psalms_22:1-6</r>
2. He is rejected by the people<r c="ps 22 6 8">@Psalms_22:6-8</r>
3. Yet he has always been faithful to God<r c="ps 22 9 10">@Psalms_22:9-10</r>
4. Powerful people have gathered against him<r c="ps 22 12 13">@Psalms_22:12-13</r>
5. He is poured out like water (blood loss)<r c="ps 22 14">@Psalms_22:14</r>
6. He is dehydrated (his tongue sticks to the roof of His mouth)<r c="ps 22 14 15">@Psalms_22:14-15</r>
7. He is brought to death<r c="ps 22 15">@Psalms_22:15</r>
8. His hands and feet are pierced<r c="ps 22 16">@Psalms_22:16</r>
9. His bones are out of joint<r c="ps 22 14, ps 22 17">[@Psalms_22:14; @Psalms_22:17]</r>
10. He's given a public execution before a hateful crowd<r c="ps 22 16 17">@Psalms_22:16-17</r>
11. They divide His garments that are divisible<r c="ps 22 18">@Psalms_22:18</r>
12. They cast lots for His tunic which is indivisible<r c="ps 22 18">@Psalms_22:18</r>
13. Despite His situation, He is delivered<r c="ps 22 21">@Psalms_22:21</r>
14. His story will be spread to all nations<r c="ps 22 27, ps 22 31">[@Psalms_22:27; @Psalms_22:31]</r>
15. Gentiles will worship the God of Israel because He has done this<r c="ps 22 27">@Psalms_22:27</r>
16. This affects people even after they die<r c="ps 22 29">@Psalms_22:29</r>

These details could not have been simply written into the Bible in order to fulfill the prophecy, because they are verifiable as expected events for that time in history --- such as casting of lots for clothes that couldn't be split up and dividing of garments which could be split up<r c="ps 22 18">@Psalms_22:18</r>, the piercing of hands and feet of crucifixion victims<r c="ps 22 16">@Psalms_22:16</r>, and that crucifixion was a public spectacle<r c="ps 22 16 17">@Psalms_22:16-17</r>. Eyewitness testimony, unto martyrdom, is even more support that Jesus was crucified. The chances of Jesus fulfilling all the prophecies that He did by chance, including those outside of His crucifixion, are essentially zero @mike_winger_prophecies_2016.

Isaiah 52 and 53 @mike_winger_fulfilled_2016-1 describe the suffering servant who would sprinkle many nations (with His blood), which the sacrifices in the Old Testament were an allusion to. This sprinkling was part of the fulfillment of God's promise to Abraham. I've already written about this prophecy in [Old Testament Salvation - The blessing of many nations, a sprinkling from Christ](../oldTestamentSalvation/oldTestamentSalvation.qmd#the-blessing-of-many-nations-a-sprinkling-from-christ).  <!--Prophecies fulfilled about Israel - that they would separate and rejoin; they rejoined as an official nation in 1948 after how long? -->
