---
title: Divorce
bibliography: merged.bib
categories: [relationships, marriage, divorce]
draft: true
---

# Divorce

&emsp;God made an amazing union in His institution of marriage, and allows us to give glory to Him by participating in it ourselves. Christ has His own bride in His body - the church. God was married to Israel in the old Testament, and Israel was to act as His body, with God as the head of this body. However, Israel was divorced from God for worshipping other gods. Idol worship by Israel, since she was married to God, was God's wife committing adultery against Him. There's not much detail given about Israel's actions, but there is a specific occurrence noted here:

> <r r="ex 32 4">"And he received them at their hand, and fashioned it with a graving tool, after he had made it a molten calf: and they said, These be thy gods, O Israel, which brought thee up out of the land of Egypt." (Exodus 32:4)</r>

It seems that God had suffered adultery for a long time, through many occurrences, and that this adultery had been committed even since their time spent in Egypt. We can see that this occurred in Egypt from the following examples:

> <r r="ezk 23 8">"Neither left she her whoredoms brought from Egypt: for in her youth they lay with her, and they bruised the breasts of her virginity, and poured their whoredom upon her." (Ezekiel 23:8)</r>

> <r r="ezk 23 17 19">"And the Babylonians came to her into the bed of love, and they defiled her with their whoredom, and she was polluted with them, and her mind was alienated from them. So she discovered her whoredoms, and discovered her nakedness: then my mind was alienated from her, like as my mind was alienated from her sister. Yet she multiplied her whoredoms, in calling to remembrance the days of her youth, wherein she had played the harlot in the land of Egypt." (Ezekiel 23:17-19)</r>

> <r r="ezk 23 27">"Thus will I make thy lewdness to cease from thee, and thy whoredom brought from the land of Egypt: so that thou shalt not lift up thine eyes unto them, nor remember Egypt any more." (Ezekiel 23:27)</r>

And, we see God's divorce here:

> <r r="Je 3 8">"And I saw, when for all the causes whereby backsliding Israel committed adultery I had put her away, and given her a bill of divorce; yet her treacherous sister Judah feared not, but went and played the harlot also." (Jeremiah 3:8)</r>

&emsp;God describes the wicked heart of Israel in great detail, showing Israel as His wife who had made herself a prostitute for other men on every hill, and under every tree<r c="je 2 20">@Jeremiah_2:20</r> <r c="je 3 6">@Jeremiah_3:6</r>, and as one so brazen and unashamed<r c="je 3 2 3">@Jeremiah_3:2-3</r> that she wouldn't even blush about it; Israel had no embarrassment for her whoredom with many men. She sought after other men as a donkey in heat would<r c="je 2 24">@Jeremiah_2:24</r>, lusting after their large genitals and horse-like emissions<r c="ezk 23 20">@Ezekiel_23:20</r>, and giving her breasts to them<r c="ezk 23 8">@Ezekiel_23:8</r> as if they did not already belong to another. She didn't even wish for these men to pursue her before giving herself to them in adultery<r c="je 2 24">@Jeremiah_2:24</r>, and even chased them herself until her shoes had worn holes in them, and her throat was dry from thirst<r c="je 2 25">@Jeremiah_2:25</r>.

&emsp;Hopefully this description helps us understand the absolute depravity and long-term unrepentance that God suffered before divorcing Israel. This was not just one occurrence of adultery that He divorced because of, but many occurrences. It was also after many repeated refusals by His wife to return to Him. In sum, these actions of God show that even though divorce is possible for adultery, God wills that marriages be restored in spite of it, if the offender confesses and repents. If God suffered Israel this much, we should be willing to reflect this image before ending a marriage, and it appears that only after unrepentant adultery should divorce be used.

## Define divorce
&emsp;The entire discussion of marriage, divorce, and remarriage - especially when discussing details in the Word - often becomes muddled by differing definitions. Miscommunications are also more common for complex ideas and scenarios.

&emsp;A somewhat common believe is that divorce inherently breaks a marriage on its own and justifies any remarriage. However, this belief is not universal and causes misunderstandings.
1. One person may be suggesting that a particular issue justifies divorce, yet while they have in mind that divorce for this particular issue only allows for separation (with reunion being required after confession and repentance), the listener may take it to mean that both divorce and remarriage are justified.
2. When one attempts to give examples of divorce - without making a claim about whether that example is of a justified divorce - some may take the example as describing a justified divorce. 

Problem 2 may be compounded with problem 1: In this scenario, if I say, for example, that divorce for life-threatening physical abuse is justified, I may intend for it to mean that the abused spouse can separate with the understanding that they'll rejoin their spouse when confessed and repented to, and that remarriage isn't an option during the separation period; however, a given listener may take it to mean that physical abuse justifies divorce, and then apply it along with their presumption that all divorce justifies remarriage to conclude that abuse justifies remarriage after divorce. Perhaps the context of the abuse being physical at all is lost on them at some point, and then they take the saying to mean that any kind of abuse justifies divorce and remarriage.

&emsp;Take for example the discussion of remarriage. I may question for a given scenario whether someone can remarry after a divorce. Someone may be confused about whether remarriage is referring to rejoining to the spouse who was divorced, or marrying someone else, and believe I'm referring to one when I'm speaking about the other.

&emsp;Take for example discussions of adultery. If someone says simply, "Adultery is sex outside of marriage.", one may take it to mean what was intended (which was that adultery is a sexual act conducted outside of the bounds of an existing marriage), while another may take the saying to mean "Adultery includes sex before marriage" (since that could count as being "outside" of a marriage). Then they may consider fornication to be a subset of adultery rather than vice versa.

&emsp; Hopefully the previous statements give a clear image of just how convoluted the entire discussion may get. However, I'd like to attempt to define divorce, share what the Word says about it, share what I believe the Word is saying, and give some sources that I hope are helpful in bringing understanding to the topic.

&emsp;As a short definition, I'll say divorce is simply one spouse declaring the dissolution of a marriage, followed by either spouse physically leaving the relationship and refusing to live with the other.

There are several questions this differing of definitions brings up:
- Does divorce mean the complete dissolution of the marriage, in the sense that remarriage is justifiable?
- Does divorce only mean separation, as a temporary ending of the relationship which must be restored if possible?
	- Is divorce for a reason that doesn't justify remarriage justifiable? Is it permissible - as in, can the church permit it?
- Could divorce be either of the first two bullets depending on the situation?
	- The Word says adultery or abandonment by an unbeliever justify remarriage.
	- Divorces that don't justify remarriage have happened, and supposing that remarriage hasn't happened, those marriages should be restored.
- Could divorce be both of first two bullets, supposing that remarriage (to a different spouse) is justifiable in a situation where the original marriage could be restored?
- Must a marriage that can be restored be restored? This question could be taken 2 different ways.
	1. If confession and repentance don't matter, then perhaps it's technically always the case that marriage can and should be restored.
	2. Is it mandatory to restore a marriage after a divorce when the offended party has been confessed and repented to?



Someone who divorced, whether it was justifiable or not, may not have divorced for a reason that justified remarriage. Another who divorced may have suffered adultery from someone who refuses to confess and repent, which does appear to justify remarriage after divorce.


## Justifications for divorce

### Does failure to fulfill duties justify divorce?
&emsp;It's commonly said that in the old testament, both husband and wife have duties to each other, and that if they don't provide sustenance, clothing, and conjugal (sexual) rights to each other - generally with the husband working, within the world, to provide the raw cloth and food materials, and the woman providing the refined products, within the home, of clothing items and prepared meals - then the offended party has the right to divorce. The passage often cited in this is:

> <r r="ex 21 7 11">"And if a man sell his daughter to be a maidservant, she shall not go out as the menservants do. If she please not her master, who hath betrothed her to himself, then shall he let her be redeemed: to sell her unto a strange nation he shall have no power, seeing he hath dealt deceitfully with her. And if he have betrothed her unto his son, he shall deal with her after the manner of daughters. If he take him another wife; her food, her raiment, and her duty of marriage, shall he not diminish. And if he do not these three unto her, then shall she go out free without money." (Exodus 21:7-11)</r>

<!-- &emsp;I could make an argument that this passage is part of a law that was specifically given to these people at this time, not to us under our current law - and also that this scenario, as a subset of their law, described only how to treat female maidservants in polygamous marriages who were denied their marital duties; context and specificity do matter, after all, and generalization isn't always appropriate. At this time, male servants were to go free after their service<r c="ex 21 2">@Exodus_21:2</r>, and female servants were not to go free since they were expected to be taken in marriage by their master after their service (the above verse explains this by mentioning the betrothal and deceitful dealing that happened afterward); however, in this case, the maidservant was to go free rather than to be kept in a polygamous marriage where her duties were denied to her. Was her being set free required simply because her duties were denied to her? Was it because her husband had married another woman without divorcing his first wife? <answer /> We cannot divorce (let the maidservant go free in this scenario) because of a failure to fulfill duties within a marriage <r c="mt 19 9">@Matthew_19:9</r>. -->

<!-- &emsp;As far as the law relates to this argument, Paul does say, <r r="ga 3 24 25">"Wherefore the law was our schoolmaster to bring us unto Christ, that we might be justified by faith. But after that faith is come, we are no longer under a schoolmaster." (Galatians 3:24-25)</r>, so it may be that none of the law listed here is of concern to us except for what we learn from it about God's overall plans. The only support I have for this concept being specific to the maidservant is that it's within a section discussing laws that apply to servants; I find it hard to be sure about the level of specificity to apply. The polygamy part of the argument seems to be the most relevant to me. It seems that God considers polygamy to be a form of adultery, because in marriage two become one flesh <r c="mt 19 5 6">@Matthew_19:5-6</r>; it also seems to be adultery because if we consider the New Testament consideration of divorce, it seems that God would now allow divorce to take place for something short of adultery<r c="mt 19 9">@Matthew_19:9</r>, or abandonment by an unbeliever<r c="1 co 7 15">@1_Corinthians_7:15</r>. -->

<!-- &emsp;This argument that divorce is supported when a spouse fails to fulfill their duties is also sometimes cited as coming from Deuteronomy 21<r c="de 21 11 14">@Deuteronomy_21:11-14</r>; however - read carefully - this passage which is similar in syntax to the one noted from Exodus 21<r c="ex 21 2">@Exodus_21:2</r> does not specifically say that the woman was married before she was to be set free. There's some recognition of the ignorance about whether she was married in the verse in Deuteronomy, with some believing that her being dishonored was that she was married, and then divorced @gill_deuteronomy_nodate. However, both passages mention that the woman would not be sold, and that this lack of ability to sell her was because she was either dealt with deceitfully (in Exodus), or humbled/dishonored (in Deuteronomy). I would say - because of the parallel phrasing, and since we know the verse in Deuteronomy was talking about a an unfulfilled betrothal - that Exodus is speaking about an unfulfilled betrothal as well, meaning that this verse isn't related to the argument about divorce. -->

<!-- &emsp;A verse which may also seem similar in syntax, but seems to me to be a different subject is Deuteronomy Deuteronomy 24:1-4: -->

<!-- > <r r="de 24 1 4">"When a man hath taken a wife, and married her, and it come to pass that she find no favor in his eyes, because he hath found some uncleanness in her: then let him write her a bill of divorcement, and give it in her hand, and send her out of his house. And when she is departed out of his house, she may go and be another man's wife. And if the latter husband hate her, and write her a bill of divorcement, and giveth it in her hand, and sendeth her out of his house; or if the latter husband die, which took her to be his wife; Her former husband, which sent her away, may not take her again to be his wife, after that she is defiled; for that is abomination before the LORD: and thou shalt not cause the land to sin, which the LORD thy God giveth thee for an inheritance." (Deuteronomy 24:1-4)</r> -->

<!-- This verse seems to be speaking of divorce after marriage; though it does seem similar in that a woman has been defiled, this is different from the wording of being dealt with deceitfully, or being humbled. To defile someone sounds more serious than humbling, dishonoring, or dealing with in a deceitful manner. It seem sthat the uncleanness here would refer to the sexual immorality that Jesus mentions <r c="mt 19 9">@Matthew_19:9</r> <explain? /> -->


## Justifications for divorce and remarriage

&emsp;I'm more confident in the argument coming from Matthew 19:9<r c="mt 19 9">@Matthew_19:9</r>. As a short definition, I'll say divorce is simply one spouse declaring the dissolution of a marriage, followed by either spouse physically leaving the relationship of and refusing to live with the other. Some believe that this dissolution of the marriage frees them to marry another. However, this verse makes it clear that divorce does not in itself allow remarriage.

> <r r="mt 19 9">"And I say unto you, Whosoever shall put away his wife, except it be for fornication, and shall marry another, committeth adultery: and whoso marrieth her which is put away doth commit adultery." (Matthew 19:9)</r>

The KJV translation uses the words fornication and adultery here. We generally consider fornication to be engaging in a sexual act before marriage, and adultery to be engaging in a sexual act with someone other than one's spouse after marriage. However, this verse isn't saying that someone can divorce their spouse if they find out that they engaged in a sexual act before they were married to them. The word translated into fornication is the Greek word "Porneia". It often believed that Jesus used this word to refer to every form of fornication, including things such as incest and beastiality, rather than just adultery.

Even if divorce is justified because of unrepentant adultery, I'd wonder, because of God's plan to redeem and remarry Israel, whether we should really ever divorce and remarry a different person than one's previous spouse.

https://bible.org/seriespage/7-teaching-jesus-divorce-matthew-193-12-mark-102-12

<!-- &emsp; Before explaining some more detail about the context of this verse, I'd like to explain my main contention with the way this verse is usually used. At the first reading, people often see the word wife used, and that her duties of marriage should be met, with failure to do so meaning that she goes free, and assume that this applies to all marriages, since it's referring to a marriage after all. However, this verse is part of a larger section which is specifically laying out rules about how servants are to be treated; if you zoom out further, you see that this is part of a set of laws which are given to a certain group of people at the time. The question then becomes whether these laws apply to us. The simple answer is that these are not our laws; these laws were given to these people, and we have our own laws under our own governments today. If that argument doesn't convince you immediately, let me put it in a different light; several verses after this, we also read:

> <r r="ex 21 23 25">"And if any mischief follow, then thou shalt give life for life, Eye for eye, tooth for tooth, hand for hand, foot for foot, Burning for burning, wound for wound, stripe for stripe." (Exodus 21:23-25)</r>

This is the "eye for an eye" verse that's often cited, and is echoed in Leviticus<r c="lv 24 17 21">@Leviticus_24:17-21</r> and Deuteronomy<r c="de 19 21">@Deuteronomy_19:21</r>. So, this is given as a part of the surrounding law formerly referenced. If the argument is made that these laws apply to us today, then this argument must be reconciled with the fact that Jesus contradicts these la

&emsp; They fail to understand the admittedly complex situation that's being laid out in detail because the situation being described is very specific and virtually non-existent anymore. Before explaining my main contention with the way this verse is often used, I would question, because of the specificity of this verse, whether it applies to all marriages. Without explaining too thoroughly, this verse is explaining what to do in a very specific scenario; in this scenario, a daughter was purchased by a man to be a maidservant and he was expected to marry her after her service of six years<r c="ex 21 2">@Exodus_21:2</r>. He decided he would not marry her after her service, and so is considered to have dealt deceitfully with her. He can giver her to his son as a wife in this case, and if his son decides to marry another woman -->


<!-- &emsp;The first thing I'd point out, without any consideration of the social situation at hand, is that this is already an abnormal marriage that falls outside of God's will for marriage. Though we understand marriage to be ideally between one man and one woman in the modern church<r c="de 17 17">@Deuteronomy_17:17</r> <r c="1 ti 3 12">@1_Timothy_3:12</r>, polygamy was common practice in the old testament, and men would often take more than one wife; God had allowed polygamy in the old testament, though He did forbid it. This passage concerns a polygamous marriage, and technically only applies to them, since that is simply all it specifically speaks of. However, before I take this concept of specificity any further, I want to explain what the entire situation in this passage is.

&emsp;The passage is explaining a situation wherein a daughter is sold as a maidservant by her father to another man. If after the six years that she was bound to serve<r c="ex 21 2">@Exodus_21:2</r>, the master who bought her decides that she is not worth marrying, he will be considered to have "dealt deceitfully with her". The idea is that in buying her as a maidservant, if she served in a fit enough manner to be a good wife, the purchaser would be expected to marry her, and that is why (in this example) he would be considered to have dealt deceitfully with her. If this master didn't want to marry her, he could offer her to his son as a wife, and treat her as a daughter. Finally, this case of letting her go free is seen after the son marries her, then marries another woman, and denies his wife who was the maidservant her marital duties which he also owes her. In this specific situation, where the son puts another wife before this wife who was once a maidservant to the point that he fails to provide the three listed duties, then she is to go free without money. Whether 

&emsp; I think people would be even more discouraged from using this verse as modern law if they realize the surrounding verses which say that a servants wife and children will belong to the master if the master gave the wife to the male servant, that this male servant may become a servant for life, that . <r r="ex 21 12 13">"He that smiteth a man, so that he die, shall be surely put to death. And if a man lie not in wait, but God deliver him into his hand; then I will appoint thee a place whither he shall flee." (Exodus 21:12-13)</r>. Yet, this is not how our modern laws work, and it will not be enforced this way.

Because of this principle, you could also argue that it only applies to polygamous marriages where the first wife was a maidservant, the maidservant's marital duties are diminished,  It doesn't speak about whether divorce is acceptable for failure to provide duties in a monogamous marriage (which we'll get to later) so it's technically logically wrong to apply this verse to more than what it directly speaks about. -->

## How people try to justify divorce
- Jesus says that divorce was allowed because of the hardness of hearts. Include what hardness of hearts led to - a woman being doomed to prostitution because of non-divorce, so divorce was the lesser evil, and so allowed. https://www.bereanpatriot.com/what-jesus-meant-by-adultery-in-matthew-chapters-5-19/ -- This link says that Jesus in Matthew 19 is referring to putting away, which is said to be different from divorce. However, from Mike winger, https://youtu.be/Bcq6yZ_EjPg, It's clear that "apoluo" is used for both putting away and divorce, I believe.

Matthew 19 3 9 - Since Jesus was addressing the question about sending away and giving a writing of divorcement, I think his statement on "putting away" has to be addressing divorce as well, perhaps using the broadest term of separation to cover every kind of separation, not to distinguish between them (are they the same word still though?). It wouldn't make sense in this context if that wasn't the case.    If it means strictly putting away without divorce, then verse 9 would be saying it's okay to separate and remarry without divorce as long as it was because of adultery. That would mean adultery itself breaks the marriage (not divorce), but we know that's not the case because God tolerated the adultery of Israel several times (check on this). If so, I don't see how that could be the case. If put away in verse 9 is referring to doing so without writs of divorcement, then you can read it as saying, "You can put away your wife without a writ of divorce if it's because she committed adultery.", and this is clearly not true due to Matthew 5:32. Matthew 5:32 seems to suggest that divorce is still required to end a marriage in the case of adultery, because its wording means that someone can be divorced for sexual immorality (which obviously requires divorce subsequent to that sexual immorality); This verse also uses put away and divorce interchangeably in the KJV for the same Greek root word, without any mention of a "writ of divorce" that the other verse includes adjacent to the word "put away".

Also the interchanging in KJV of put away and divorce for the same word in Mat 5:32 leaves you with only one of two possible scenarios being true because of the verse's other vocabulary. Either put away and divorce mean the same thing, or all men who marry any divorced woman become adulterers. I don't think the latter is true, because a woman is re-marriageable after divorce in the case that she was the victim of her former husband's adultery. So, we're left with the words meaning the same thing. In case you wonder, yes, the instances of "put away" and "divorce" here (in the KJV) are the same Greek word.

Keep in mind that God's plan is to redeem Israel and include her in the body, even after divorce. What does that mean within our marriages and separations if we're to reflect him - that marriage is life-long.


- The Bible mentions adultery and abandonment by a non-believer as possible reasons to divorce. So that seems to mean that believers who are separated from their believing spouse are still "bound" to them. There's also the common claim that abuse justifies divorce, and for some reason it's claimed to be part of the Bible, perhaps because divorces used to be possible due to failure to fulfill duties. However, the New Testament teaches us that failure to fulfill duties on the part of one's spouse is not a reason to divorce them, and the Bible is also silent on abuse being a justification for divorce, although it seems to go without saying that you can defend yourself and flee/separate for your safety. Honestly, cases where someone is genuinely concerned for their life seem exceptionally rare, and this seems like another case of finding a rare exception to justify a terrible social rule being made to justify divorce for an undefined blanket reason which will inevitably be taken advantage of. [Write about abuse being used blanketly, from notes].

## God hates divorce
- Jesus says that divorce and remarriage creates adulterers unless adultery it was committed against them. Should you stay in a relationship after being "cheated on"? The Bible doesn't demand it, but didn't God only divorce Israel after repeated idolatry (spiritual adultery), when it was clear that they were actively refusing to make Him their head?

## How do the verses about not associating with sinners work when you have a sinning spouse?
- 1 cor 5 11 12, eph 5 3 7, 2 tim 3 1 5
- Gill on 1 co 5 11 12
- you can't leave an unbeliever who is happy to live with you as a spouse, though they sin, so you can't use sin as an excuse to divorce.
- also if it's adultery to divorce and remarry for less than adultery, then there's no divorce in the sense that people wish for it, only separation or adultery.
- Along with the verses that say don't company with unbelievers, it's said that those who don't take care of family are worse than unbelievers 1 tim 5 8, so should we disassociate even more so from a spouse who refuses to fulfill their duty and is worse than an unbeliever because of this? This doesn't support divorce; you still have duties to fulfill to a spouse, and must do this even when they don't fulfill theirs. If this is not the case, then you support divorce for unrepentant sin, which makes all sin cause the threat of divorce, which means anyone can divorce, and this goes against Jesus saying that if you divorce for something other than adultery, you commit adultery if you remarry, and cause the person you divorce to commit adultery.


## Does pornography count as adultery?
&emsp;Does hate count as literal murder?
><r r="1 jn 3 15">"Whosoever hateth his brother is a murderer: and ye know that no murderer hath eternal life abiding in him." (1 John 3:15)</r>

As with many parts of the Word, this is interpreted in accordance with of the rest of scripture. So, this first isn't to be interpreted as saying that if you hate, you've physically committed murder, or that someone who has murdered cannot is disqualified from eternal life altogether. The murderer who has no eternal life abiding in him is in the present tense, meaning one who has not put their faith in God for their redemption and repented of their sin cannot have eternal life within them. If a murderer continues with a murderous heart, without confession and repentance, they've not accepted God as their redeemer, putting away the former self. Interpret this along with:

><r r="mt 5 27 28">"Ye have heard that it was said by them of old time, Thou shalt not commit adultery: But I say unto you, That whosoever looketh on a woman to lust after her hath committed adultery with her already in his heart." (Matthew 5:27-28)</r>.

This shows us that it is not only the act of sin which condemns us, but a heart which wills toward a sin. Human's cannot know one's heart, so our judges convict based on actions and evidence. However, God knows our hearts, and can judge us for holding evil in them. That is why the word also says:

<r r="james 4 17">"Therefore to him that knoweth to do good, and doeth it not, to him it is sin." (James 4:17)</r>

These verses lead us to understand that even our heart is sinful, and not only our acts, or lack thereof.

So, we should recognize that lust does not mean that one has literally committed fornication or adultery. The question is then whether it's a sin to hold things such as hatred or lust in your heart.

If you pay attention, the verse specifically addresses adultery, which is only one engaging in a sexual act outside of an existing marriage, and does not address fornication. I believe we'd have to conclude that lust for an unmarried woman is also sin, since fornication is also a sin. So, if you continue to hold hatred or lust in your heart, it's a sin for you. The point is that we're all still in fallen flesh, and we must continue to confess and repent to God and look to his grace and mercy.

To answer the original question, we must finally ask whether sin justifies divorce, since we know we can classify lust as sin. Sin can't justify divorce in the sense of allowing remarriage because Christians are called to remain married to unbelievers, and because we're told that divorce and remarriage for something other than adultery is itself adultery.

## Forgiveness vs divorce
&emsp;I actually don't think Jesus's words - about divorce causing adultery in both spouses if the spouse hadn't committed adultery already - were suggesting that we should divorce when a spouse commits adultery. I think  he's simply stating the point that if it's done without adultery existing then you make both of yourselves adulterers. The statement can't technically be taken to mean anything more than that on it's own. If a spouse struggles with lust, perhaps even adultery, yet continues to confess and repent, how can we hold it against them while God has forgiven them, since He has also forgiven us? It seems that God only divorced Israel when they continued in unrepentant idolatry (spiritual adultery). So, perhaps it's only appropriate to divorce a spouse when they continue in unrepentant adultery. What if they seem repentant, but continue in it? We're told, <r r="mt 18 21 22">"Then came Peter to him, and said, Lord, how oft shall my brother sin against me, and I forgive him? till seven times? Jesus saith unto him, I say not unto thee, Until seven times: but, Until seventy times seven." (Matthew 18:21-22)</r>, so it seems that since only God knows their heart, we should forgive them if they confess to us and say they'll repent.
Does Jesus's exception not necessarily mean that those who divorce for adultery are right in marrying another person?

&emsp;If they fail to confess after the biblical standard of proof is brought forward, it is then clear that they don't have the love of the Father within them, and I believe then that adultery certainly constitutes a proper reason for a divorce. Note the biblical process for confronting sin; by the time divorce is happening, the body of Christ should be involved in the confrontation, and non-confession leads to disassociation from the congregation; this disassociation would also happen for sin that causes divorce, though not all sin justifies divorce. So, you may be married to one who is disassociated from the congregation. See [Redeemed Relationships](../redeemedRelationships/redeemedRelationships.qmd)
Again, abandonment.

## A consideration of non-marriage
If it seems difficult to tolerate this much sin from a spouse (that they could repeatedly sin, even if they confess and express their will to repent), Jesus says that we may forgo marriage:

><r r="mt 19 10 12">"His disciples say unto him, If the case of the man be so with his wife, it is not good to marry. But he said unto them, All men cannot receive this saying, save they to whom it is given. For there are some eunuchs, which were so born from their mother's womb: and there are some eunuchs, which were made eunuchs of men: and there be eunuchs, which have made themselves eunuchs for the kingdom of heaven's sake. He that is able to receive it, let him receive it." (Matthew 19:10-12)</r>

So, if it seems too painful for you to go through this for the sake of showing love to a spouse, consider Paul's words:

><r r="1 co 7 6 9">"But I speak this by permission, and not of commandment. For I would that all men were even as I myself. But every man hath his proper gift of God, one after this manner, and another after that. I say therefore to the unmarried and widows, It is good for them if they abide even as I. But if they cannot contain, let them marry: for it is better to marry than to burn." (1 Corinthians 7:6-9)</r>

Also, around the context of suggesting that people stay in their current state in this world, Paul says:

><r r="1 co 7 25 35">"Now concerning virgins I have no commandment of the Lord: yet I give my judgment, as one that hath obtained mercy of the Lord to be faithful. I suppose therefore that this is good for the present distress, I say, that it is good for a man so to be. Art thou bound unto a wife? seek not to be loosed. Art thou loosed from a wife? seek not a wife. But and if thou marry, thou hast not sinned; and if a virgin marry, she hath not sinned. Nevertheless such shall have trouble in the flesh: but I spare you. But this I say, brethren, the time is short: it remaineth, that both they that have wives be as though they had none; And they that weep, as though they wept not; and they that rejoice, as though they rejoiced not; and they that buy, as though they possessed not; And they that use this world, as not abusing it: for the fashion of this world passeth away. But I would have you without carefulness. He that is unmarried careth for the things that belong to the Lord, how he may please the Lord: But he that is married careth for the things that are of the world, how he may please his wife. There is difference also between a wife and a virgin. The unmarried woman careth for the things of the Lord, that she may be holy both in body and in spirit: but she that is married careth for the things of the world, how she may please her husband. And this I speak for your own profit; not that I may cast a snare upon you, but for that which is comely, and that ye may attend upon the Lord without distraction." (1 Corinthians 7:25-35)</r>


##
Can you charge someone for hating another person if you don't know their heart? No, so divorce shouldn't happen because of lusting. Perhaps you can say that you know their heart if they watch pornography, or if you were to see their actions along with it to satisfy themselves. However, even if you do know their heart, then if they confess to you and repent, can you withhold forgiveness from them? The answer must be, "No.", because we're forgiven when we confess and repent. Lust is an issue of the heart which many men struggle against, and men should continue in the effort against it, pursuing purity in mind and body. If we wish to charge people for their heart, we should realize that essentially everyone has lusted at some point, probably within their marriage, and that everyone could be divorced for that, if our standard for divorce is that it's justified because of lust. Would God will for everyone to divorce because of this? Would he rather there be no marriage at all because of the wickedness of our hearts, or would he rather that we attempt to display his heart toward his spouse in our marriages, and suffer even actual adultery to allow time for their repentance, and for us to actively seek it?

The Bible doesn't explicitly mention masturbation, but I'd leave releases to be handled by natural night-time emissions.
https://www.gotquestions.org/fornication-adultery.html

###### refine

- If someone wonders whether they should divorce someone simply because they're a sinner, since we're not supposed to associate with sinners, and since they could be called an unbeliever for continuing in unrepentant sin, then I'd reference Paul suggesting that we shouldn't divorce our unbelieving spouses if they're content to live with us. Could you still divorce them in the case of adultery or abandonment? Perhaps; the point though is that even someone's general sin doesn't justify divorcing them, since unbelievers will inevitably sin, but we're supposed to continue in marriage to them once if we're already married to them.

- The argument for divorce that references, <r r="mt 18 18">"Verily I say unto you, Whatsoever ye shall bind on earth shall be bound in heaven: and whatsoever ye shall loose on earth shall be loosed in heaven." (Matthew 18:18)</r>, to say that a divorce counts as freeing someone to marry another person ignores that the verse is in the context of the body of Christ dealing with believers who continue in sin being removed from the congregations. It is also future tense, meaning that whatever it is which will be bound is not necessarily bound in heaven yet. They also ignore that Matthew 22:30 says, <r r="mt 23 30">"And say, If we had been in the days of our fathers, we would not have been partakers with them in the blood of the prophets." (Matthew 23:30)</r>, which means that there is no marriage to be bound in heaven. It can't be marriage being spoken about here because of it being bound also in the future and that marriage will not exist in heaven.

- Argument that divorce writs make a divorce official. No, the divorce is telling your partner that the marriage is over, and removing yourself from the relationship however you do so. The divorce was only given as an official legal declaration so that someone would know you were divorced and couldn't have their spouse reclaimed later.

- 1 cor 7 10


&emsp;In trying to find which deeds allow divorce to be initiated, it seems from mt 19 that it's not supported unless someone is in unconfessed/unrepentant sin continually toward their spouse in a form that includes adultery or abandonment by an unbeliever, suggesting that there's no will to be in relationship with them any longer. Un-fulfillment of duties doesn't seem to permit divorce either. Even adultery, if confessed and repented for, cannot be held against a believer if confessed and repented for. If there's a continual confession and repentance for repeated sin, God forgives us, so how can we hold that against others, including our spouses, since we're to forgive 70 times 7 times, essentially any time we're confessed to? It seems though, that plenty of people (especially women) are okay with glossing over their own failures to accuse their spouse of failing, and act as if it's justification for their actions. Perhaps a wife refuses to fulfill her duties because her husband is not perfect? Why refuse to represent your part in the image of God? Why do you essentially say, "My spouse is failing to please me, so I'm going to be a bad spouse as well to express my dissatisfaction, and I'm justified in it!"? Isn't it the attitude of "an eye for an eye", which Jesus warns us against?

Common belief is that you can remarry if you're divorced unjustifiably. It seems that in the same way you can't divorce for refusal to fulfill duties, you also can't divorce for separation which is what unjustified divorce would count as. If your spouse who divorced you, in this scenario, marries another, then this counts as adultery, and then you may remarry.

## Jesus speaking to Jerusalem
- Matthew 23:37 treats Jerusalem as having a desolate house. Would this be Jesus saying that he wished to have Jerusalem as his body (bride), but her house was left desolate to Her, as in there were no believers for her to raise, similar to a woman who has no children from a head (a man).

##
Are mark 10 and mathew 19 9 saying the same thing about divorce although Mark doesn't include he exception clause? Is it Matthew 19 putting it in the terms that a man has to take his wife back if he divorces her "unless she commits adultery" to say - since he didn't divorce her for adultery, and remarried another, he divorced for the purpose of remarrying another? That would work with Mark when it leaves out the exception clause.
