---
Title: Intelligent Design 
Categories: []
bibliography: merged.bib
draft: true
---

## Intelligent design

DNA - 4 bit code vs 2 bit code that only takes it's true meaning when it's folded. People can't understand 2 bit code without decompiling it into higher level languages, and no one argues software with any complexity would come from random generation of zeros and ones. Even if it could, any human software with minor complexity requires automated tests that still aren't comprehensive due to time limitations. Human produced 2 bit code doesn't self-error correct if something changes within it, and we use sometimes complex checksums to even be able to see whether it has been invalidated by some hardware error in the first place. The point isn't to say we don't keep backups and restore them, but our human-written programs aren't set up to check themselves and correct themselves implicitly in their own code, and systems that do this can be complex. Gene expression is also controlled by DNA. That any useful change to a living organism is seemingly intelligently controlled without conscious input contradicts the laws of entropy that would cause random change to destroy this intelligent change, and this points to a designer who is vastly more intelligent than the collective intelligence of mankind over the course of all time. The sheer number of circumstantial inputs that can be intelligently handled (without side effects that break the balance that supports life) is staggering. Human attempts to change this through things such as mRNA modification show how small modifications to this code destroy the delicate balance of the system as a whole. Any software engineer knows that for any integrated system, changing one variable can have cascading effects, and that the only way to see these changes, and check to prevent catastrophe, is with automated testing, yet humans thought fit to experiment on themselves by modifying their biological code before developing any way to test such changes without live experiments to observe them (because we don't understand what the code is, we can't know what our changes would do before changing it). The problem is that we can't even completely comprehend 2 bit code even when it's displayed to us as a comprehensible language (before being compiled). We simply have no hope of understanding the sheer complexity behind DNA. The point is, DNA is far more complex than the collective software humans build, but no one would contend that even a simple calculator program had compiled itself from randomly generated binary values, much less that more random changes would improve it's functionality to add features such as sin(), cos(), etc. functions. Each operation would clearly have a purpose and would be organized in the code.

Cell irreducible complexity. Similar to symbiotic relationships in flowers and bees.

This and arguments for intelligent design only prove that God exists, but how do we know it's the Christian God of the Bible?
