---
title: marriageIsNotRequired
categories: [relationships, marriage]
draft: true
---
<!-- date: -->

## No, marriage is not necessary
For many people, the default position is the pursuit of marriage. Everyone should be prepared for marriage and understand what marriage represents. However, the idea that someone not pursuing marriage must be in the wrong is quite prevalent even in Christian circles, which should know better. See <a href=""> marriage is not necessary</a>. 

# Marriage is not a solution to lust
There’s an argument that Christians must marry from biblicalgenderroles.com/2018/11/27/why-mgtow-is-an-unbiblical-philosophy. Address the bullet points.

# "Because of the present distress"
Discuss because of the present distress verse, and what that means, and how it's interpreted often to simply be persecution at the time of writing. However, Paul suggests a more broad application when saying that spouses are occupied with each other rather than on pleasing God and building treasures in heaven.

Marriage is less valuable than serving God at least in this world, even if it is perfect, because it is temporary, and our service to the kingdom has eternal benefits and rewards.

Heaven is eternal with all the fruits of our labor on Earth, but our marriages are temporary in this Earth, and "we are like the angels" when in heaven.
What are the concerns of each party in non-marriage 1 cor 7?


## MGTOW
An entire section is devoted to discussing this topic

## Current laws - a present distress
Current laws are a dire distress for men, and since men are denying marriage and women partially because of this, they're indirectly becoming a distress for women as well.

Also, at the point that you give autonomy up and are owned by the state through marriage, and are subject to corrupt law to the point of enslavement through it, you must not go through with marriage, at the very least with a marriage license, which hands ownership of your children over to the state as "Fruits" of the labor of your marriage (which is considered a business partnership in law)<a href="">big john mgtow is freedom video on marriage</a>, and invites the state as head over your marriage when God is supposed to be the head. You should bring the body into subjection as Paul suggests, and I think even if you fail daily, this is better than becoming a slave – not that marriage makes you a slave, but our government along with worldly women may force you to choose physically between prison and enslavement to a women who refuses to fulfill her promise of relationship to you.

Cover duluth model, divorce statistics, divorce court and link to JP video about character assassination and state control of children
